name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:    
          distribution: 'corretto'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run lint
        run: ./gradlew lint

      - name: Run buid
        run: ./gradlew build -x test

      - uses: yutailang0119/action-android-lint@v3.1.0
        if: always()
        with:
          report-path: ./*/build/reports/*.xml
