name: Android Tests

on:    
  workflow_dispatch:

jobs:
  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          disk-size: 5GB
          script: ./gradlew connectedCheck

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
