name: Android Tests

on:    
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:    
          distribution: 'corretto'
          java-version: '11'
          
  android_tests:
    runs-on: macos-latest
    needs: setup
    steps:
      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew connectedCheck

  report:
    runs-on: ubuntu-latest
    needs: android_tests
    if: ${{ always() }}
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
