name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_jdk
      - uses: android-actions/setup-android@v2
    
      - run: ./gradlew lint
      
      - uses: yutailang0119/action-android-lint@v3.1.0
        if: always()
        with:
          report-path: ./*/build/reports/*.xml
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_jdk
      - uses: android-actions/setup-android@v2
    
      - name: Run Buid
        run: ./gradlew build -x test
