name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup_jdk

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run lint
        run: ./gradlew lint
      
      - name: Report
        uses: yutailang0119/action-android-lint@v3.1.0
        if: always()
        with:
          report-path: ./*/build/reports/*.xml
      
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Buid
        run: ./gradlew build -x test
