name: Android Tests

on:    
  workflow_dispatch:

jobs:
  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:    
          distribution: 'corretto'
          java-version: '11'

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          disk-size: 5GB
          emulator-options: -no-window -gpu host -no-snapshot -noaudio -no-boot-anim
          script: ./gradlew connectedCheck

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
